{
 "title": "Buyback Statistics",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "program",
    "label": "Program",
    "query": {
     "query": "SELECT id, name FROM alliance_auth.buybackprogram_program;"
    }
   }
  ]
 },
 "panels": [
  { "title": "$program", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "program" },
  {
   "title": "Summary Statistics",
   "type": "stat",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT \n  program.name as program_name,\n  COUNT(contract.id) as total_contracts,\n  SUM(tracking.net_price) as total_price,\n  SUM(tracking.value) as total_value,\n  SUM(contract.volume) as total_volume,\n  AVG(tracking.net_price) as average_price,\n  AVG(contract.volume) as average_volume\nFROM alliance_auth.buybackprogram_tracking as tracking\nJOIN alliance_auth.buybackprogram_program as program ON program.id = tracking.program_id\nJOIN alliance_auth.buybackprogram_contract as contract on contract.id = tracking.contract_id\nWHERE \n  $__timeFilter(contract.date_completed)\n  AND tracking.program_id IN ($program)\nGROUP BY tracking.program_id;"
    }
   ]
  },
  {
   "title": "Contracts Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT \n  $__timeGroupAlias(contract.date_completed, '1d'),\n  COUNT(contract.id) AS value\nFROM alliance_auth.buybackprogram_tracking as tracking\nJOIN alliance_auth.buybackprogram_program as program ON program.id = tracking.program_id\nJOIN alliance_auth.buybackprogram_contract as contract on contract.id = tracking.contract_id\nWHERE \n  $__timeFilter(contract.date_completed)\n  AND tracking.program_id IN ($program)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Value Per Day",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT \n  $__timeGroupAlias(contract.date_completed, '1d'),\n  SUM(tracking.value) AS value\nFROM alliance_auth.buybackprogram_tracking as tracking\nJOIN alliance_auth.buybackprogram_program as program ON program.id = tracking.program_id\nJOIN alliance_auth.buybackprogram_contract as contract on contract.id = tracking.contract_id\nWHERE \n  $__timeFilter(contract.date_completed)\n  AND tracking.program_id IN ($program)\nGROUP BY 1\nORDER BY 1"
    }
   ]
  }
 ]
}