{
 "title": "Leaderboards",
 "time": { "from": "now-30d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "corporation",
    "label": "Main Corporation",
    "query": "SELECT corporation_name from eveonline_evecorporationinfo;"
   }
  ]
 },
 "panels": [
  {
   "title": "Ratting",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT\n    main.character_name,\n    SUM(char_totals.char_sum) AS total_sum\nFROM (\n    SELECT\n        character_id,\n        SUM(amount) AS char_sum\n    FROM alliance_auth.corptools_characterwalletjournalentry\n    WHERE ref_type = \"bounty_prizes\"\n        AND $__timeFilter(date)\n    GROUP BY character_id\n) AS char_totals\nINNER JOIN alliance_auth.corptools_characteraudit as ca\n    ON ca.id = char_totals.character_id\nINNER JOIN alliance_auth.authentication_characterownership AS own \n    ON ca.character_id = own.character_id\nINNER JOIN alliance_auth.authentication_userprofile AS up \n    ON own.user_id = up.user_id\nINNER JOIN alliance_auth.eveonline_evecharacter AS main \n    ON up.main_character_id = main.id\nWHERE\n  main.corporation_name = \"$corporation\"\nGROUP BY\n    main.id\nORDER BY total_sum desc\nLIMIT 20;"
    }
   ]
  },
  {
   "title": "Mining",
   "type": "barchart",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "WITH top_miners AS (\n    SELECT\n        up.main_character_id,\n        SUM(ledger.quantity) AS grand_total\n    FROM alliance_auth.corptools_characterminingledger AS ledger\n    INNER JOIN alliance_auth.corptools_characteraudit AS ca \n        ON ca.id = ledger.character_id\n    INNER JOIN alliance_auth.authentication_characterownership AS own \n        ON ca.character_id = own.character_id\n    INNER JOIN alliance_auth.authentication_userprofile AS up \n        ON own.user_id = up.user_id\n    INNER JOIN alliance_auth.eveonline_evecharacter AS main \n        ON up.main_character_id = main.id\n    WHERE $__timeFilter(ledger.date)\n      AND main.corporation_name = \"$corporation\"\n    GROUP BY up.main_character_id\n    ORDER BY grand_total DESC\n    LIMIT 20\n)\nSELECT\n    main.character_name,\n    ig.name,\n    SUM(ledger.quantity) AS total_sum,\n    tm.grand_total\nFROM alliance_auth.corptools_characterminingledger AS ledger\nINNER JOIN alliance_auth.corptools_eveitemtype AS it \n    ON it.type_id = ledger.type_name_id\nINNER JOIN alliance_auth.corptools_eveitemgroup AS ig \n    ON ig.group_id = it.group_id\nINNER JOIN alliance_auth.corptools_characteraudit AS ca \n    ON ca.id = ledger.character_id\nINNER JOIN alliance_auth.authentication_characterownership AS own \n    ON ca.character_id = own.character_id\nINNER JOIN alliance_auth.authentication_userprofile AS up \n    ON own.user_id = up.user_id\nINNER JOIN alliance_auth.eveonline_evecharacter AS main \n    ON up.main_character_id = main.id\nINNER JOIN top_miners AS tm\n    ON main.id = tm.main_character_id\nWHERE $__timeFilter(ledger.date)\nGROUP BY main.id, ig.group_id, tm.grand_total\nORDER BY tm.grand_total DESC, total_sum DESC"
    }
   ]
  },
  {
   "title": "Corp Jobs Installed",
   "type": "barchart",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "alliance_auth",
     "rawSql": "SELECT\n    main.character_name,\n    SUM(char_totals.char_sum) AS total_sum\nFROM (\n    SELECT\n        installer_id,\n        COUNT(*) AS char_sum\n    FROM alliance_auth.corptools_corporationindustryjob\n    WHERE\n      $__timeFilter(start_date)\n    GROUP BY installer_id\n) AS char_totals\nINNER JOIN alliance_auth.eveonline_evecharacter as c\n    ON c.character_id = char_totals.installer_id\nINNER JOIN alliance_auth.authentication_characterownership AS own \n    ON c.id = own.character_id\nINNER JOIN alliance_auth.authentication_userprofile AS up \n    ON own.user_id = up.user_id\nINNER JOIN alliance_auth.eveonline_evecharacter AS main \n    ON up.main_character_id = main.id\nWHERE\n  main.corporation_name = \"$corporation\"\nGROUP BY\n    main.id\nORDER BY total_sum desc\nLIMIT 20;"
    }
   ]
  }
 ]
}